[package]
name = "pdf"
version = "0.1.0"
authors = ["GregoireHENRY <gregoire.henry@ipsa.fr>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
printpdf = "0.3.2"
freetype-rs = "0.24.0"
image = "0.23.4"

[profile.release]
lto = true
